version: "3"

networks:
  app-net:
    driver: bridge

volumes:
  pg_data:

services:
  postgres:
    image: postgres
    container_name: "pg"
    environment:
      - POSTGRES_PASSWORD=12345678"
    networks:
      - app-net
    restart: always
    env_file: ./.env
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    depends_on:
      - postgres
    container_name: "w11"
    build: .
    networks:
      - app-net
    restart:
      always
    env_file: ./.env
    ports:
      - 3000:3000



